// This file is a generated file. It may have been generated by a build tool or script in the project.
const path = require('path');
const { sequelizeConfig } = require(path.resolve(__dirname, '../dist/src/config/index'));

module.exports = sequelizeConfig;